version: "3.9"

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    environment:
      DOMAIN: "https://vault-server.tail630429.ts.net"
      ADMIN_TOKEN: ${ADMIN_TOKEN}
      WEBSOCKET_ENABLED: true
      SIGNUPS_ALLOWED: false
    volumes:
      - ./vw-data:/data
    expose:
      - "80"

  caddy:
    image: caddy:2.8
    container_name: caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/data:/data
      - ./caddy/config:/config
      - /etc/caddy/certs:/etc/caddy/certs:ro
    depends_on:
      - vaultwarden
